In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[38, 43],
       [82, 90],
       [ 5, 85],
       [46, 82],
       [66, 82],
       [67,  0],
       [12, 21],
       [37, 60],
       [16, 33],
       [64, 85]])

In [6]:
scalar_model = MinMaxScaler()

In [7]:
type(scalar_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scalar_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scalar_model.transform(data)

array([[0.42857143, 0.47777778],
       [1.        , 1.        ],
       [0.        , 0.94444444],
       [0.53246753, 0.91111111],
       [0.79220779, 0.91111111],
       [0.80519481, 0.        ],
       [0.09090909, 0.23333333],
       [0.41558442, 0.66666667],
       [0.14285714, 0.36666667],
       [0.76623377, 0.94444444]])

In [12]:
scalar_model.fit_transform(data) #does fit and transform steps at once

array([[0.42857143, 0.47777778],
       [1.        , 1.        ],
       [0.        , 0.94444444],
       [0.53246753, 0.91111111],
       [0.79220779, 0.91111111],
       [0.80519481, 0.        ],
       [0.09090909, 0.23333333],
       [0.41558442, 0.66666667],
       [0.14285714, 0.36666667],
       [0.76623377, 0.94444444]])

In [13]:
import pandas as pd

In [14]:
my_data = np.random.randint(0,101,(50,4))

In [15]:
my_data

array([[  8,  33,  52,  34],
       [ 18,  78,  37,  42],
       [ 69,  95,  88,  99],
       [ 70,  91,  80,  23],
       [ 86,  20,  84,  93],
       [ 27,   4,  25,   6],
       [ 96,  24,  98,  98],
       [ 98,  54,   8,  76],
       [ 22,  89,  37,  96],
       [ 29,   4,  40,  29],
       [ 22,  42,  92,  86],
       [ 51,  55,  46,  34],
       [ 69,  56,  49,  22],
       [ 73,  36,  49,  67],
       [ 37,  24,  85,  50],
       [ 56,  34,  20,  21],
       [ 66,  89,  80,   3],
       [ 73,  27,  47,  34],
       [ 92,  82,  78,  93],
       [ 50,   5,  17,  66],
       [ 61,  31,  40,  40],
       [  8,  14,  88,  15],
       [ 38,  91,   9,  28],
       [ 46,  60,  92,  85],
       [ 20,  35,  33,   6],
       [ 73,  90,  52,  11],
       [100,  17,  40,  29],
       [ 33,  68,  46,  96],
       [ 61,  48,   7,  47],
       [  0,  15,  81,  19],
       [ 73,  12,  66,  30],
       [ 27,  72,   2,  91],
       [ 31,  30,  78,  94],
       [ 47,  36,  95,  70],
       [ 15,   1,  77,   8],
       [ 98,  72,  95,   9],
       [  3,  46,  64,  80],
       [ 93,  55,  43,  74],
       [ 50,  60,  26,  35],
       [ 71,  20,  22,   8],
       [ 71,   7,  54,  18],
       [ 51,  20,  13, 100],
       [ 80,  17,   6,  58],
       [ 56,  83,  90,  36],
       [ 78,  55,   6,  76],
       [ 95,  67,  52,  43],
       [  7,  72,  31,  71],
       [ 15,   0,  82,  96],
       [ 23,  60,  87,  25],
       [ 65,  75,  28,  32]])

In [18]:
df = pd.DataFrame(data = my_data)

In [19]:
df

      0   1   2    3
0     8  33  52   34
1    18  78  37   42
2    69  95  88   99
3    70  91  80   23
4    86  20  84   93
5    27   4  25    6
6    96  24  98   98
7    98  54   8   76
8    22  89  37   96
9    29   4  40   29
10   22  42  92   86
11   51  55  46   34
12   69  56  49   22
13   73  36  49   67
14   37  24  85   50
15   56  34  20   21
16   66  89  80    3
17   73  27  47   34
18   92  82  78   93
19   50   5  17   66
20   61  31  40   40
21    8  14  88   15
22   38  91   9   28
23   46  60  92   85
24   20  35  33    6
25   73  90  52   11
26  100  17  40   29
27   33  68  46   96
28   61  48   7   47
29    0  15  81   19
30   73  12  66   30
31   27  72   2   91
32   31  30  78   94
33   47  36  95   70
34   15   1  77    8
35   98  72  95    9
36    3  46  64   80
37   93  55  43   74
38   50  60  26   35
39   71  20  22    8
40   71   7  54   18
41   51  20  13  100
42   80  17   6   58
43   56  83  90   36
44   78  55   6   76
45   95  67  52   43
46    7  72  31   71
47   15   0  82   96
48   23  60  87   25
49   65  75  28   32

In [20]:
df = pd.DataFrame(data = my_data, columns=['f1','f2','f3','label']) #supevised learning with 3 features and 1 label

In [21]:
df

     f1  f2  f3  label
0     8  33  52     34
1    18  78  37     42
2    69  95  88     99
3    70  91  80     23
4    86  20  84     93
5    27   4  25      6
6    96  24  98     98
7    98  54   8     76
8    22  89  37     96
9    29   4  40     29
10   22  42  92     86
11   51  55  46     34
12   69  56  49     22
13   73  36  49     67
14   37  24  85     50
15   56  34  20     21
16   66  89  80      3
17   73  27  47     34
18   92  82  78     93
19   50   5  17     66
20   61  31  40     40
21    8  14  88     15
22   38  91   9     28
23   46  60  92     85
24   20  35  33      6
25   73  90  52     11
26  100  17  40     29
27   33  68  46     96
28   61  48   7     47
29    0  15  81     19
30   73  12  66     30
31   27  72   2     91
32   31  30  78     94
33   47  36  95     70
34   15   1  77      8
35   98  72  95      9
36    3  46  64     80
37   93  55  43     74
38   50  60  26     35
39   71  20  22      8
40   71   7  54     18
41   51  20  13    100
42   80  17   6     58
43   56  83  90     36
44   78  55   6     76
45   95  67  52     43
46    7  72  31     71
47   15   0  82     96
48   23  60  87     25
49   65  75  28     32

In [22]:
X=df[['f1','f2','f3']]

In [23]:
X

     f1  f2  f3
0     8  33  52
1    18  78  37
2    69  95  88
3    70  91  80
4    86  20  84
5    27   4  25
6    96  24  98
7    98  54   8
8    22  89  37
9    29   4  40
10   22  42  92
11   51  55  46
12   69  56  49
13   73  36  49
14   37  24  85
15   56  34  20
16   66  89  80
17   73  27  47
18   92  82  78
19   50   5  17
20   61  31  40
21    8  14  88
22   38  91   9
23   46  60  92
24   20  35  33
25   73  90  52
26  100  17  40
27   33  68  46
28   61  48   7
29    0  15  81
30   73  12  66
31   27  72   2
32   31  30  78
33   47  36  95
34   15   1  77
35   98  72  95
36    3  46  64
37   93  55  43
38   50  60  26
39   71  20  22
40   71   7  54
41   51  20  13
42   80  17   6
43   56  83  90
44   78  55   6
45   95  67  52
46    7  72  31
47   15   0  82
48   23  60  87
49   65  75  28

In [24]:
y=df['label']

In [25]:
y

0      34
1      42
2      99
3      23
4      93
5       6
6      98
7      76
8      96
9      29
10     86
11     34
12     22
13     67
14     50
15     21
16      3
17     34
18     93
19     66
20     40
21     15
22     28
23     85
24      6
25     11
26     29
27     96
28     47
29     19
30     30
31     91
32     94
33     70
34      8
35      9
36     80
37     74
38     35
39      8
40     18
41    100
42     58
43     36
44     76
45     43
46     71
47     96
48     25
49     32
Name: label, dtype: int32

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [29]:
X_test.shape

(15, 3)

In [30]:
X_train.shape

(35, 3)